version: '3'


services:
  api: 
    build: 
      context: .
      dockerfile: Dockerfile

    command: sh -c "python3 manage.py makemigrations --no-input
                            && python3 manage.py migrate --no-input
                            && python3 manage.py runserver 0.0.0.0:8000"
                            # && python3 manage.py crontab add
                            # && NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program python3 manage.py runserver 0.0.0.0:5000"
    restart: on-failure
    # volumes: 
    #   - static_files:/usr/src/app/static
    ports: 
      - "8000:8000"
    env_file:
      - .env

# volumes: 
#   static_files:
