# Generated by Django 4.1.3 on 2023-01-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_family_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.FloatField(default=0),
        ),
    ]
