# Generated by Django 4.1.3 on 2023-02-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='family_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.family'),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='service_provider_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service_provider'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
