# Generated by Django 4.1.3 on 2023-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='sp88665', max_length=128),
            preserve_default=False,
        ),
    ]
