# Generated by Django 4.1.3 on 2023-02-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
