# Generated by Django 4.1.3 on 2023-02-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_city_pincode_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
