# Generated by Django 4.1.3 on 2023-02-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social_login',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
