# Generated by Django 4.1.3 on 2023-02-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_order_data_order_ispaid_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.FloatField(default=0),
        ),
    ]
