# Generated by Django 4.1.3 on 2023-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_order_ispaid_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
