# Generated by Django 4.1.3 on 2023-02-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
